hosts = {
  "win" => "192.168.2.23" 
}

Vagrant.configure("2") do |config|
  
  config.vm.box = "mwrock/Windows2016"
	hosts.each do |name, ip|
 
    config.vm.define name do |machine|
 
      machine.vm.network :private_network, ip: ip
 
      machine.vm.provider "virtualbox" do |v|
 
        v.name = name
 
      end
    end
  end
  
end
