---
- name: Instalacion de Apache
  yum: name=httpd state=latest
  notify:
    - start apache

- name: Eliminar el index.html original
  file:
    state: absent
    path: /var/www/html/index.html
  register: html_old
  ignore_errors: True

- name: Subir el index.html que queramos
  copy: src=index.html dest=/var/www/html mode=0644
  when: html_old is success


