- hosts: all
  become: true
  
  tasks:
    - name: Instalar última versión de nginx
      apt: name=nginx state=latest
    - name: start nginx
      service:
        name: nginx
        state: started