---
- hosts: all
  remote_user: root
  tasks:
          # upload ssh key                
          - authorized_key:
                  user: root
                  state: present
                  manage_dir: yes
                  key: "{{ lookup('file', '/path/to/your/www_id_rsa.pub') }}"
