- hosts: all
  tasks:
  - stat:
      path: /home/vagrant/prueba2.txt mode=0777
    register: result

  - file:
      path: /home/vagrant/prueba2.txt
      state: touch
      mode: 0644
    when: result.stat.exists == false

